version: '3'
services:
  app:
    environment:
      - SPRING_PROFILES_ACTIVE=loadtest
      - COUPON_STRATEGY=redis
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=10
      - SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE=5
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=5000
