spring:
  profiles:
    active: local
  data:
    redis:
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1

server:
  port: 8080

logging:
  level:
    root: INFO
    com.yourpackage: DEBUG

coupon:
  stock-sync-delay-ms: 60000
  scheduler:
    stock-sync-enabled: false